# Generated by Django 4.1.7 on 2023-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record", name="address", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record", name="mobile", field=models.CharField(max_length=15),
        ),
    ]
